---
sudo: required
dist: trusty

language: c

addons:
  apt:
    packages:
    - debhelper
    - debian-archive-keyring
    - fakeroot
    - lcov
    - pbuilder
    - python-docutils

compiler:
  - clang
  - gcc

env:
  matrix:
    - CFLAGS=-O0
    - CFLAGS=-O1
    - CFLAGS=-O2
    - CFLAGS=-O3
    - CFLAGS=-Os
    - MAKE_TARGET=distcheck

matrix:
  include:
    - compiler: gcc
      env: MAKE_TARGET=pdebuild PDEBUILD_OPTS='-- --debug'
    - compiler: gcc
      env: MAKE_TARGET=lcov CONFIGURE_FLAGS=--enable-lcov
  allow_failures:
    - compiler: gcc
      env: MAKE_TARGET=pdebuild PDEBUILD_OPTS='-- --debug'

install:
  - set -e
  - travis/install_varnish.sh
  - travis/create_pbuilder.sh

script:
  - ./bootstrap $CONFIGURE_FLAGS
  - make ${MAKE_TARGET:-check}

after_success:
  - test "$MAKE_TARGET" = lcov || exit 0
  - cp vmod-querystring.info codecov.info
  - bash <(curl -s https://codecov.io/bash) -X gcov -X coveragepy
