#!/bin/sh
#
# Written by Dridi Boukelmoune <dridi.boukelmoune@gmail.com>
#
# This file is in the public domain.

set -e
set -u

srcdir=$(dirname "$0")

pkg-config --exists --print-errors varnishapi

VARNISHAPI_DATAROOTDIR=$(pkg-config --variable=datarootdir varnishapi)
export VARNISHAPI_DATAROOTDIR

autoreconf -i "$srcdir"

"$srcdir"/configure \
	--enable-maintainer-mode \
	--enable-silent-rules \
	--enable-warnings \
	--enable-docs \
	"$@" \
	QS_VARNISH_VERSION=6.0.6
